# Generated by Django 6.0.3 on 2026-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('portfolio_url', models.TextField(blank=True, null=True)),
                ('experience_years', models.TextField(blank=True, null=True)),
                ('starting_price', models.TextField(blank=True, null=True)),
                ('turnaround_time', models.TextField(blank=True, null=True)),
                ('custom_skills', models.JSONField(blank=True, default=list, null=True)),
                ('verification_status', models.TextField(blank=True, default='unverified', null=True)),
                ('response_time', models.TextField(blank=True, null=True)),
                ('cover_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'creators',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.TextField()),
                ('date', models.DateField()),
                ('profile_views', models.IntegerField(default=0, null=True)),
                ('service_clicks', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'daily_analytics',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.TextField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_credentials',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'ordering': ['label'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='deadlinenotification',
            options={'managed': False, 'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ordertimeline',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userwallet',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
